services:
  nodejs-server:
    image: node:14-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start

    # Optional: Specify environment variables if needed
    environment:
      NODE_ENV: production